default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: easy_desafio_backend_development
  username: easy_desafio_backend
  password: 'sorvete123'
  host: localhost

test:
  <<: *default
  database: easy_desafio_backend_test
  username: easy_desafio_backend
  password: 'sorvete123'
  host: localhost

# production:
#   <<: *default
#   database: easy_desafio_backend_production
#   username: easy_desafio_backend
#   password: <%= ENV["EASY_DESAFIO_BACKEND_DATABASE_PASSWORD"] %>
